apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varselbjelle-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-varselbjelle-api-secrets
    - configmap: loginservice-idporten
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-varselbjelle-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-varselbjelle-api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-varselbjelle-api/metrics
  secureLogs:
    enabled: true
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dittnav-event-handler
        - application: dittnav-event-aggregator
    inbound:
      rules:
        - namespace: personbruker
          application: innloggingsstatus
        - namespace: personbruker
          application: nav-dekoratoren-api
  ingresses:
    - "https://person.nav.no/tms-varselbjelle-api"
    - "https://www.nav.no/tms-varselbjelle-api"
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 64Mi
