name: Bygg og publiser docker-image for main

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        image: ${{ env.IMAGE }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: --configuration-cache build installDist

      - name: Bygg, tag og push Docker image
        uses: navikt/pb-common-gh-actions/docker-publish@v2
        with:
          TAG_LATEST: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release i git-repo-et
        run: |
          TAG="$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(git log -1 --pretty='%h')"
          git config user.name "Team Personbruker CI"
          git config user.email "personbruker@nav.no"
          git tag $TAG
          git push origin $TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        cluster: [dev-gcp, prod-gcp]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy-er til ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v1
        env:
          REF: ${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: ./nais/${{ matrix.cluster }}/nais.yaml
          VAR: version=${{ needs.build.outputs.image }}
          PRINT_PAYLOAD: true
