name: Bygg branch

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: --configuration-cache build installDist
